### ISSUE TITLE
Batch

### ISSUE THREAD

**Issue by Ahsankkhan** [parbatpk/parbat#10]
|  Verb | Input | Returns| Description | Business Rule(s) | 
|  --- | --- | --- | --- | --- | 
|  GET |  |DataTable / Array | List | - | 
|  GET (OrgUnit/long)| id  |DataTable / Array | List | OrgUnitID = id |
|  GET (Curriculum/long)| id |DataTable / Array | List | CurriculumID = id | 
|  GET(long) | PK | BO | Find | Returns NotFound() if record does not exist | 
|  Delete(long) | PK | - | Delete | Returns BadRequest() if record does not exists | 
|  POST |[FromBody] BO  | BO | Insert | - | 
|  PUT |[FromBody] BO  | - | Insert | Returns BadRequest() if record does not exists |

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing this issue
