### ISSUE TITLE
Curriculum

### ISSUE THREAD

**Issue by Ahsankkhan** [parbatpk/parbat#14]
|  Verb | Input | Returns| Description | Business Rule(s) | 
|  --- | --- | --- | --- | --- | 
|  GET |  |DataTable / Array | List | **R1*** | 
|  GET(long) | PK | BO | Find | Returns NotFound() if record does not exist + **R1***  
|  GET(OwnerUnit/long) | OwnerUnitID | DataTable/Array | List all curriculums having given OwnerUnitID | - | 
|  GET(CurriculumType/long) | CurriculumTypeID | DataTable/Array | List all curriculums having given CurriculumTypeID | - | 
|  Delete(long) | PK | - | Delete | Returns BadRequest() if record does not exists  | 
|  POST |[FromBody] BO  | BO | Insert | + **R2*** | 
|  PUT |[FromBody] BO  | - | Insert | Returns BadRequest() if record does not exists + **R3*** +**R4*** +**R2*** | 

## Rules
R1 = All foreign keys must return with IDs and their name
R2 = TotalCourses >=0 and TotalCreditHrs >=0 
R3 =  TotalCourses >= Sum (Components.TotalCourses) for this curriculum 
R4 =  TotalCreditHrs >= Sum (Components.Totalcredit) for this curriculum

### For R3 and R4 
- Create an SP that returns the total number of components, the sum of TotalCredit, and the sum of TotalCourses for the given CurriculumID
-  Use this SP in BO for Update/PUT to verify these rules

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing this issue
