### ISSUE TITLE
StudentProgram

### ISSUE THREAD

**Issue by Ahsankkhan** [parbatpk/parbat#18]
## Stories
- A student can enroll in one or more programs
- A student can enroll in another program if all previous program in which he/she enrolled has EndDate
- If Curriculum is not defined the student's Batch's curriculum will be used
- We can override Batch's curriculum by defining student's curriculum in this entity
- Minor curriculum is defined for each student separately, not batch-wise

## Services
|  Verb | Input | Returns| Description | Business Rule(s) | 
|  --- | --- | --- | --- | --- | 
|  GET |  |DataTable / Array | List | - | 
|  GET(Student/long) |  |DataTable / Array | List all programs for which a student is registered | StudentID = id | 
|  GET(long) | PK | BO | Find | Returns NotFound() if record does not exist | 
|  Delete(long) | PK | - | Delete | Returns BadRequest() if record does not exists | 
|  POST |[FromBody] BO  | BO | Insert | - | 
|  PUT |[FromBody] BO  | - | Insert | Returns BadRequest() if record does not exists |

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing this issue
