### ISSUE TITLE
StudentGroup

### ISSUE THREAD

**Issue by Ahsankkhan** [parbatpk/parbat#40]
|  Verb | Input | Returns| Description | Business Rule(s) | 
|  --- | --- | --- | --- | --- | 
|  GET |  |DataTable / Array | List | - | 
|  GET(long) | PK | BO | Find | Returns NotFound() if record does not exist | 
|  Delete(long) | PK | - | Delete | Returns BadRequest() if record does not exists | 
|  POST |[FromBody] BO  | BO | Insert | - | 
|  PUT |[FromBody] BO  | - | Insert | Returns BadRequest() if record does not exists | 

# Student Group
- [CRUD-L] /StudentGroup
- [GET] /StudentGroup/\{GroupID\}/Student : list all students belong to the given GroupId
- [GET] /StudentGroup/\{GropuID\}/Student(StudentGroupSearch): list all students that can fulfill the criteria given in the object but should not be part of the given group
  - StudentGroupSearch: Student.Name,Student.Identifier, Student.BatchID, OrgUnitID
- [POST] /StudentGruop/\{GroupID\}/Student (List<StudentProgramID>) : add these students for the group
- [DELETE] /StudentGruop/\{GroupID\}/Student (List<long>) : delete these students for the group

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing this issue
