### ISSUE TITLE
Term

### ISSUE THREAD

**Issue by Ahsankkhan** [parbatpk/parbat#42]
|  Verb | Input | Returns| Description | Business Rule(s) | 
|  --- | --- | --- | --- | --- | 
|  GET |  |DataTable / Array | List | - | 
|  GET(long) | PK | BO | Find | Returns NotFound() if record does not exist | 
|  Delete(long) | PK | - | Delete | Returns BadRequest() if record does not exists | 
|  POST |[FromBody] BO  | BO | Insert | R1 | 
|  PUT |[FromBody] BO  | - | Insert | Returns BadRequest() if record does not exists  +R1 | 

- [GET] /Term/\{TermID\}/Course: list all courses already offered for the given term 
  - Output: Offering.*, Course.*, OrgUnit.ShortName, Semester.ShortName
- [DELETE] /Term/\{TermID\}/Course/: delete these courses for the given term
  - Parameter: [Body]List<OfferingID>  (an array of long) 
- [POST] /Term/\{TermID\}/Course/List<Offering> : add these Offering's objects into the database

## Business Rules
- [ ] R1 = End Date must be greater than Start Date
- [ ]

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing issue
