### ISSUE TITLE
Incorrect Exception Handling

### ISSUE THREAD

**Issue by MuhammadRafay151** [parbatpk/parbat#51]
![image](https://user-images.githubusercontent.com/46870378/115460425-afbe7280-a241-11eb-96d5-288da6de5ab9.png)
there are incorrect exception handling at multiple places which will create issues on client-side for example in this action for every type of error  it returns a bad request

**Comment by MuhammadRafay151** [comment]
another example is that if exception raises due to DB connection fails it will return 400 instead of  500 or 503

**Comment by mqpasta** [comment]
@Ahsankkhan We have to discuss and find an appropriate solution.

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing this issue
