### ISSUE TITLE
Organization Unit Types Delete

### ISSUE THREAD

**Issue by MuhammadRafay151** [parbatpk/parbat#52]
![image](https://user-images.githubusercontent.com/46870378/115463969-d7afd500-a245-11eb-90e2-7a4a3c40b6a0.png)

**Comment by mqpasta** [comment]
@MuhammadRafay151 did you run combine_sp.sql file on the database?

**Comment by MuhammadRafay151** [comment]
yes i do

**Comment by maazk9119** [comment]
implemented this in new structure @mqpasta closing this issue
