### ISSUE TITLE
StudentGroup Api documentation missing in swagger 

### ISSUE THREAD

**Issue by MuhammadAamir21** [parbatpk/parbat#76]
![image](https://user-images.githubusercontent.com/51251914/121779757-ba004b80-cbb6-11eb-9012-cf2201400202.png)

There is no proper structure of api in swagger documentation.

**Comment by maazk9119** [comment]
use json syntax. It's working. 
You can give input in json format.
Get all the student Group and see the output there will be json result. Follow it while hitting save or update api.
